---
services:
  roundcubedb:
    image: mysql:5.7
    container_name: roundcubedb
    restart: unless-stopped
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
    ports:
      - 10.0.0.1:${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  roundcubemail:
    image: roundcube/roundcubemail:1.6.9-apache
    container_name: roundcubemail
    restart: unless-stopped
    depends_on:
      - roundcubedb
    volumes:
      - ${WWW_DATA_PATH}:/var/www/html
    ports:
      - 10.0.0.1:${ROUNDCUBE_PORT}:80
    env_file:
      - .env

networks: {}
...
