---
services:
  roundcubedb:
    image: mysql:5.7
    container_name: roundcubedb
    restart: unless-stopped
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - 10.0.0.1:34010:5432
      - 10.0.0.1:33006:3306
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube-mysql-pw
      - MYSQL_DATABASE=roundcubemail
  roundcubemail:
    image: roundcube/roundcubemail:1.6.9-apache
    container_name: roundcubemail
    restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    volumes:
      - ./www:/var/www/html
    ports:
      - 10.0.0.1:9001:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.adjutor.xyz
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.adjutor.xyz
networks: {}

### Optional: add a full mail server stack to use with Roundcube like https://github.com/docker-mailserver/docker-mailserver
#   mailserver:
#     image: mailserver/docker-mailserver:14.0.0
#     hostname: mail.example.org
#     ...  # for more options see https://github.com/docker-mailserver/docker-mailserver#examples
