services:
  nginx-fpm-alpine:
    image: privatebin/nginx-fpm-alpine:1.7.7
    restart: unless-stopped
    read_only: true
    ports:
      - 10.0.0.1:8081:8080
    volumes:
      - $PWD/privatebin-data:/srv/data
      - $PWD/conf.php:/srv/cfg/conf.php:ro
networks: {}
