services:
  anubis-nginx:
    image: ghcr.io/techarohq/anubis:latest
    environment:
      BIND: :8923
      DIFFICULTY: "5"
      METRICS_BIND: :9090
      SERVE_ROBOTS_TXT: "true"
      TARGET: http://nginx
    ports:
      - 10.0.0.1:8923:8923
  nginx:
    image: nginx
    volumes:
      - ./www:/usr/share/nginx/html
networks: {}
