services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    ports:
      - 10.0.0.1:9100:9100
    container_name: node_exporter
    command: --path.rootfs=/host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
networks: {}
