services:
  semaphore_db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - semaphore_postgres:/var/lib/postgresql/data
    networks:
      - semaphore_network
  semaphore:
    image: semaphoreui/semaphore:v2.13.12
    env_file:
      - .env
    ports:
      - 10.0.0.1:3080:3000
    depends_on:
      - semaphore_db
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_HOST: semaphore_db
      SEMAPHORE_DB_NAME: semaphore
      SEMAPHORE_DB_USER: ${SEMAPHORE_DB_USER}
      SEMAPHORE_DB_PASS: ${SEMAPHORE_DB_PASS}
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN}
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_EMAIL_SENDER: ${SEMAPHORE_EMAIL_SENDER}
      SEMAPHORE_EMAIL_HOST: ${SEMAPHORE_EMAIL_HOST}
      SEMAPHORE_EMAIL_PORT: ${SEMAPHORE_EMAIL_PORT}
      SEMAPHORE_EMAIL_USERNAME: ${SEMAPHORE_EMAIL_USERNAME}
      SEMAPHORE_EMAIL_PASSWORD: ${SEMAPHORE_EMAIL_PASSWORD}
      SEMAPHORE_EMAIL_SECURE: "True"
      SEMAPHORE_GOTIFY_ALERT: "True"
      SEMAPHORE_GOTIFY_URL: https://notify.adjutor.eu.org
      SEMAPHORE_GOTIFY_TOKEN: ${SEMAPHORE_GOTIFY_TOKEN}
    volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore
      - semaphore_tmp:/tmp/semaphore
    networks:
      - semaphore_network
volumes:
  semaphore_data: null
  semaphore_config: null
  semaphore_tmp: null
  semaphore_postgres: null
networks:
  semaphore_network:
    driver: bridge
